name = "tiger-ai-team"
main = "worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "tiger-ai-team-db"
database_id = "1901d404-def3-4452-a9ba-5cc66bb252db"

[triggers]
crons = ["0 6 * * *"]
[vars]
WEBSITE_URL = "https://tiger-event.com"
ZOHO_CLIENT_ID = "1000.IEC1QBNRC3X4D02ZK1HUXTN5QBIX7H"
ZOHO_REDIRECT_URI = "https://tiger-ai-team.mohdjarour.workers.dev/zoho-callback"
ZOHO_ACCOUNTS = '[{"email":"mohamedjarour@tiger-event.com","refresh_token":"1000.c5dc8c9b1dfbc20d7382180f727f7e1f.675e39fbc458e33be6e5e150ced08a31"},{"email":"info.tiger@tiger-event.com","refresh_token":"1000.999c1f4773c49fc5026e53e7e75e67e8.c0eae92fd13a386a108ca023554b5bac"},{"email":"tiger@tiger-event.com","refresh_token":"1000.074e6c28f3dc31e23417137c3b0ca5dc.1f19a01342bcdfbf4ec4963e5414a3d5"},{"email":"mohammed.alshekih@tiger-event.com","refresh_token":"1000.4dd41b64e5e14b0798652d5060244875.9396829cc2c1302677620de881525e7b"}]'
